* Introduction
A stackless coroutine library for C/C++, implemented yield, await, concurrency and channel.

* Overview
#+BEGIN_SRC C
#include "cogo.h"

co_declare(CoroutineName, T var, ...)
{
co_begin:

    //
    // user code
    //

co_end:;
}
#+END_SRC

* Example
*** Natural number generator
#+BEGIN_SRC C
#include "cogo.h"
#include <stdio.h>

co_declare(Nat, int value)
{
co_begin:

    for (co_this->value = 0; ; co_this->value++) {
        co_yield;
    }

co_end:;
}

int main()
{
    Nat n = co_make(Nat);

    CO_STEP(&n);
    printf("n.value: %d\n", n.value);   // n.value: 0

    CO_STEP(&n);
    printf("n.value: %d\n", n.value);   // n.value: 1

    CO_STEP(&n);
    printf("n.value: %d\n", n.value);   // n.value: 2
}
#+END_SRC

*** Fibonacci number
#+BEGIN_SRC C
#include "cogo.h"
#include <stdio.h>
#include <stdlib.h>

co_declare(Fibonacci, int n, int v, Fibonacci* fib_n1, Fibonacci* fib_n2)
{
co_begin:

    if (co_this->n == 0) {          // f(0) = 0
        co_this->v = 0;
    } else if (co_this->n == 1) {   // f(1) = 1
        co_this->v = 1;
    } else {                        // f(n) = f(n-1) + f(n-2)
        co_this->fib_n1 = malloc(sizeof(*co_this->fib_n1));
        co_this->fib_n2 = malloc(sizeof(*co_this->fib_n2));

        *co_this->fib_n1 = co_make(Fibonacci, n-1);
        *co_this->fib_n2 = co_make(Fibonacci, n-2);
        co_await(co_this->fib_n1);  // run f(n-1)
        co_await(co_this->fib_n2);  // run f(n-2)
        co_this->v = co_this->fib_n1->v + co_this->fib_n2->v;

        free(co_this->fib_n1);
        free(co_this->fib_n2);
    }

co_end:;
}

int main()
{
    Fibonacci fib = co_make(Fibonacci, 9);
    CO_RUN(&fib);
    printf("%d\n", fib.v);  // 34
}
#+END_SRC

*** Channel
#+BEGIN_SRC C
#include "cogo.h"
#include <iostream>
#include <time.h>

// send a signal to <reader> when writer finished
class writer_t : public co_t {
    CHAN_T<0> &chan;
    unsigned long i;

    void operator()()
    {
        co_begin();

        for (; i > 0; i--) {        // countdown
            co_yield();
        }
        CHAN_WRITE(chan, this);  // send finish signal

        co_end();
    }

public:
    writer_t(CHAN_T<0> &chan, unsigned long i)
        : chan(chan)
        , i(i)
    {}
};


// wait <writer>s finished
class reader_t : public co_t {
    CHAN_T<0> &chan;
    writer_t   writers[2];
    void      *msg;
    time_t     t;

    void operator()()
    {
        co_begin();

        // create 2 new coroutines
        CO_START(writers[0]);
        CO_START(writers[1]);

        // wait finish
        CHAN_READ(chan, msg);    // receive finish signal
        std::cout << msg << " finished: " << clock() * 1.0 / CLOCKS_PER_SEC << "s\n";
        CHAN_READ(chan, msg);    // receive finish signal
        std::cout << msg << " finished: " << clock() * 1.0 / CLOCKS_PER_SEC << "s\n";

        co_end();
    }

public:
    reader_t(CHAN_T<0> &&chan)
        : chan(chan)
        , writers{writer_t(chan, 1ul << 26), writer_t(chan, 1ul << 27)}
    {}
};

int main()
{
    // 0x7ffeee071960 finished: 4.08375s
    // 0x7ffeee0719a8 finished: 6.18752s
    reader_t(CHAN_T<0>()).run();
}
#+END_SRC

* Getting Started
** Requirement
- C99

*** C++
#+BEGIN_SRC C++
//
// 1. include header "cogo.h"
//
#include "cogo.h"
#include <stdio.h>

//
// 2. define a class that inherit co_t
//
class PrintN : public co_t {
    //
    // declare local variables, parameters, return values for coroutine function as member variables
    //
    int i;

    //
    // 3. override operator(), which has the type "void ()"
    //
    void operator()()
    {
        //
        // 4. set coroutine begin
        //
        co_begin();

        //
        // 5. user code (no local variable allowed, declare as member variable instead)
        //
        for (i = 0; i < 7; i++) {
            printf("%p:%d\n", this, i);
            co_yield();    // yield
        }

        //
        // 4. set coroutine end
        //
        co_end();
    }

    //
    // 6. define constructor if needed
    //
// public:
    // PrintN(...)
    // {
    //    ...
    // }
};

                                // 2. inherit co_t
class CoroutineExample : public co_t {
                                //
    PrintN coroutine1;          // declare local variables
    PrintN coroutine2;          //

    void operator()()           // 3. override operator()
    {
        co_begin();             // 4. coroutine begin

                                // 5. user code
        CO_START(coroutine1);   // add coroutine1 to scheduler
        CO_START(coroutine2);   // add coroutine2 to scheduler
                                //

        co_end();               // 4. coroutine end
    }

// public:
    // CoroutineExample(...)    // 6. define constructor if needed
    // {
    //    ...
    // }
};


int main()
{
    // Run until finish all coroutines.
    // Output:
    //  0x8f0:0
    //  0x8f0:1
    //  0x918:0
    //  0x8f0:2
    //  0x918:1
    //  0x8f0:3
    //  ...
    CoroutineExample().run();
}
#+END_SRC

*** C
#+BEGIN_SRC C
#include "cogo.h"           // 1. include header

typedef struct {            // 2. inherit co_t
    co_t co;                // put co_t in first

                            //
    int value;              // declare local variables, return values of coroutine function
                            //
} nat_gen_t;

void nat_gen(nat_gen_t *co) // 3. define coroutine function with the type "void (co_t *)"
{
    co_begin(co);           // 4. set Coroutine begin

                            // 5. user code
    for (co->value = 0; ; co->value++) {
        co_yield(co);       // yield
    }

    co_end(co);             // 4. set coroutine end
}
                            // 6. define constructor, init co_t member with co_make()
#define NAT_GEN()   ((nat_gen_t){.co = co_make(nat_gen),})


int main(void)
{
    nat_gen_t ng = NAT_GEN();

    nat_gen(&ng);           // ng.value = 0
    nat_gen(&ng);           // ng.value = 1
    nat_gen(&ng);           // ng.value = 2

    return 0;
}
#+END_SRC

* API
*** C++
- co_begin ()      :: Set coroutine begin.
                      List with the line numbers (__LINE__) of macros
                        *co_yield()*,
                        *CO_RETURN()*,
                        *co_await()*,
                        *CO_START()*,
                        *co_wait()*,
                        *co_broadcast()*,
                      or omit if GNUC extension enabled.
- co_end   ()      :: Set coroutine end.
- co_yield ()      :: Yield.
- CO_RETURN()      :: Return with ending coroutine.
- co_await(co_t &) :: Await another coroutine to finish.
- CO_START(co_t &) :: Add a coroutine to scheduler to run.
- co_wait     (co_blocking_t &) :: block current coroutine until notified.
- co_broadcast(co_blocking_t &) :: wake up all coroutines blocked by specified co_blocking_t.

- obj.run()   :: Run until all coroutines finished, with /obj/ as entry (like main()).
- obj.state() :: Return the current running state of coroutine /obj/.
  -  0: ready
  - >0: running
  - <0: stopped, coroutine is finished

*** C
- co_begin (co_t *)         :: Mark coroutine begin.
- co_end   (co_t *)         :: Mark coroutine end.
- co_yield (co_t *)         :: Yield from coroutine.
- CO_RETURN(co_t *)         :: Return with ending coroutine.
- co_await (co_t *, co_t *) :: Await another coroutine to finish.
- CO_START (co_t *, co_t *) :: Add a coroutine to scheduler to run.

- CO_RUN  (co_t *) :: loop running until finish all coroutines
+ CO_STATE(co_t *) :: Return the current running state of coroutine /obj/.
  -  0: ready
  - >0: running
  - <0: stopped, coroutine is finished

* See Also
- [[https://www.chiark.greenend.org.uk/~sgtatham/coroutines.html][Coroutines in C]]
- [[http://dunkels.com/adam/pt/][Protothreads]]    
