// Copyright (c) 2018-2024 Moxi Color
//
// Use of this source code is governed by a MIT-style license
// that can be found in the LICENSE file or at https://opensource.org/licenses/MIT

/// @file
#ifndef ZY_MACRO_UTILS_H_
#define ZY_MACRO_UTILS_H_

#define ZY_IDENTITY(...)      __VA_ARGS__
#define ZY_COMMA(...)         ,

#define ZY_TO_STRING(...)     ZY_DO1_TO_STRING(__VA_ARGS__)
#define ZY_DO1_TO_STRING(...) #__VA_ARGS__

/// Get the Nth element of arguments.
/// @return the Nth element of arguments.
/// @pre argc > 0
// e.g. ZY_GET1(        , ...,A3,A2,A1,A0)  -> A1 (argc == 0, bug, want A0)
//      ZY_GET1(_1      , ...,A3,A2,A1,A0)  -> A1 (argc == 1, ok)
//      ZY_GET1(_1,_2   , ...,A3,A2,A1,A0)  -> A2 (argc == 2, ok)
//      ZY_GET1(_1,_2,_3, ...,A3,A2,A1,A0)  -> A3 (argc == 3, ok)
#define ZY_GET1(...)          ZY_DO1_GET1(__VA_ARGS__)
#define ZY_DO1_GET1(                                              \
    _1, _2, _3, _4, _5, _6, _7, _8, _9, _10,                      \
    _11, _12, _13, _14, _15, _16, _17, _18, _19, _20,             \
    _21, _22, _23, _24, _25, _26, _27, _28, _29, _30,             \
    _31, _32, _33, _34, _35, _36, _37, _38, _39, _40,             \
    _41, _42, _43, _44, _45, _46, _47, _48, _49, _50,             \
    _51, _52, _53, _54, _55, _56, _57, _58, _59, _60,             \
    _61, _62, _63, _64, _65, _66, _67, _68, _69, _70,             \
    _71, _72, _73, _74, _75, _76, _77, _78, _79, _80,             \
    _81, _82, _83, _84, _85, _86, _87, _88, _89, _90,             \
    _91, _92, _93, _94, _95, _96, _97, _98, _99, _100,            \
    _101, _102, _103, _104, _105, _106, _107, _108, _109, _110,   \
    _111, _112, _113, _114, _115, _116, _117, _118, _119, _120,   \
    _121, _122, _123, _124, _125, _126, _127, _128, _129, N, ...) \
  N

#define ZY_COUNT1(...) ZY_GET1(__VA_ARGS__, ZY_COUNT_V)
#define ZY_COUNT_V     ZY_IDENTITY(                   \
    129, 128, 127, 126, 125, 124, 123, 122, 121, 120, \
    119, 118, 117, 116, 115, 114, 113, 112, 111, 110, \
    109, 108, 107, 106, 105, 104, 103, 102, 101, 100, \
    99, 98, 97, 96, 95, 94, 93, 92, 91, 90,           \
    89, 88, 87, 86, 85, 84, 83, 82, 81, 80,           \
    79, 78, 77, 76, 75, 74, 73, 72, 71, 70,           \
    69, 68, 67, 66, 65, 64, 63, 62, 61, 60,           \
    59, 58, 57, 56, 55, 54, 53, 52, 51, 50,           \
    49, 48, 47, 46, 45, 44, 43, 42, 41, 40,           \
    39, 38, 37, 36, 35, 34, 33, 32, 31, 30,           \
    29, 28, 27, 26, 25, 24, 23, 22, 21, 20,           \
    19, 18, 17, 16, 15, 14, 13, 12, 11, 10,           \
    9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

#define ZY_HAS_COMMA(...) ZY_GET1(__VA_ARGS__, ZY_HAS_COMMA_V)
#define ZY_HAS_COMMA_V    ZY_IDENTITY( \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,      \
    1, 1, 1, 1, 1, 1, 1, 1, 0, 0)

#define ZY_STRIP_PAREN(...)              ZY_DO1_STRIP_PAREN(ZY_HAS_COMMA(__VA_ARGS__), ZY_HAS_COMMA(ZY_COMMA __VA_ARGS__), __VA_ARGS__)
#define ZY_DO1_STRIP_PAREN(...)          ZY_DO2_STRIP_PAREN(__VA_ARGS__)
#define ZY_DO2_STRIP_PAREN(N, M, ...)    ZY_DO3_STRIP_PAREN_##N##M(__VA_ARGS__)
#define ZY_DO3_STRIP_PAREN_11(...)       __VA_ARGS__
#define ZY_DO3_STRIP_PAREN_10(...)       __VA_ARGS__
#define ZY_DO3_STRIP_PAREN_01(X)         ZY_IDENTITY X
#define ZY_DO3_STRIP_PAREN_00(X)         X

// ZY_MAP1(SEP, (F1, F2, ...), A1, A2, ...)
// -> ...(F2(F1(A1)) SEP
//    ...(F2(F1(A2)) SEP
//    ...
#define ZY_MAP1(SEP, FS, ...)            ZY_DO1_MAP1(ZY_COUNT1(__VA_ARGS__), ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO1_MAP1(N, SEP, FS, ...)     ZY_DO2_MAP1(N, ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO2_MAP1(N, SEP, FS, ...)     ZY_DO3_MAP1_##N(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_1(SEP, FS, A)        ZY_PIPE1(A, ZY_STRIP_PAREN(FS))
#define ZY_DO3_MAP1_2(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_1(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_3(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_2(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_4(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_3(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_5(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_4(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_6(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_5(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_7(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_6(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_8(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_7(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_9(SEP, FS, A, ...)   ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_8(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_10(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_9(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_11(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_10(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_12(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_11(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_13(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_12(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_14(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_13(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_15(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_14(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_16(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_15(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_17(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_16(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_18(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_17(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_19(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_18(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_20(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_19(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_21(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_20(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_22(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_21(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_23(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_22(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_24(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_23(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_25(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_24(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_26(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_25(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_27(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_26(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_28(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_27(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_29(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_28(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_30(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_29(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_31(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_30(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_32(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_31(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_33(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_32(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_34(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_33(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_35(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_34(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_36(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_35(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_37(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_36(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_38(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_37(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_39(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_38(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_40(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_39(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_41(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_40(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_42(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_41(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_43(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_42(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_44(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_43(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_45(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_44(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_46(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_45(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_47(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_46(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_48(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_47(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_49(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_48(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_50(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_49(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_51(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_50(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_52(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_51(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_53(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_52(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_54(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_53(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_55(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_54(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_56(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_55(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_57(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_56(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_58(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_57(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_59(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_58(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_60(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_59(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_61(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_60(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_62(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_61(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_63(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_62(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_64(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_63(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_65(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_64(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_66(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_65(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_67(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_66(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_68(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_67(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_69(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_68(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_70(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_69(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_71(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_70(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_72(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_71(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_73(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_72(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_74(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_73(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_75(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_74(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_76(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_75(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_77(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_76(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_78(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_77(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_79(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_78(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_80(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_79(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_81(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_80(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_82(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_81(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_83(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_82(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_84(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_83(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_85(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_84(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_86(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_85(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_87(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_86(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_88(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_87(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_89(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_88(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_90(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_89(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_91(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_90(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_92(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_91(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_93(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_92(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_94(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_93(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_95(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_94(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_96(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_95(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_97(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_96(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_98(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_97(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_99(SEP, FS, A, ...)  ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_98(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_100(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_99(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_101(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_100(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_102(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_101(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_103(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_102(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_104(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_103(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_105(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_104(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_106(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_105(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_107(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_106(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_108(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_107(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_109(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_108(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_110(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_109(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_111(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_110(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_112(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_111(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_113(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_112(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_114(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_113(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_115(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_114(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_116(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_115(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_117(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_116(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_118(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_117(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_119(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_118(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_120(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_119(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_121(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_120(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_122(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_121(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_123(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_122(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_124(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_123(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_125(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_124(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_126(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_125(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_127(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_126(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_128(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_127(ZY_IDENTITY(SEP), FS, __VA_ARGS__)
#define ZY_DO3_MAP1_129(SEP, FS, A, ...) ZY_PIPE1(A, ZY_STRIP_PAREN(FS)) SEP ZY_DO3_MAP1_128(ZY_IDENTITY(SEP), FS, __VA_ARGS__)

#define ZY_PIPE1(A, ...)                 ZY_DO1_PIPE1(ZY_COUNT1(__VA_ARGS__), A, __VA_ARGS__)
#define ZY_DO1_PIPE1(N, A, ...)          ZY_DO2_PIPE1(N, A, __VA_ARGS__)
#define ZY_DO2_PIPE1(N, A, ...)          ZY_DO3_PIPE1_##N(A, __VA_ARGS__)
#define ZY_DO3_PIPE1_1(A, F)             ZY_APPLY(F, ZY_STRIP_PAREN(A))
#define ZY_DO3_PIPE1_2(A, F, ...)        ZY_DO3_PIPE1_1(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_3(A, F, ...)        ZY_DO3_PIPE1_2(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_4(A, F, ...)        ZY_DO3_PIPE1_3(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_5(A, F, ...)        ZY_DO3_PIPE1_4(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_6(A, F, ...)        ZY_DO3_PIPE1_5(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_7(A, F, ...)        ZY_DO3_PIPE1_6(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_8(A, F, ...)        ZY_DO3_PIPE1_7(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_9(A, F, ...)        ZY_DO3_PIPE1_8(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_10(A, F, ...)       ZY_DO3_PIPE1_9(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_11(A, F, ...)       ZY_DO3_PIPE1_10(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_12(A, F, ...)       ZY_DO3_PIPE1_11(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_13(A, F, ...)       ZY_DO3_PIPE1_12(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_14(A, F, ...)       ZY_DO3_PIPE1_13(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_15(A, F, ...)       ZY_DO3_PIPE1_14(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_16(A, F, ...)       ZY_DO3_PIPE1_15(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_17(A, F, ...)       ZY_DO3_PIPE1_16(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_18(A, F, ...)       ZY_DO3_PIPE1_17(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_19(A, F, ...)       ZY_DO3_PIPE1_18(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_20(A, F, ...)       ZY_DO3_PIPE1_19(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_21(A, F, ...)       ZY_DO3_PIPE1_20(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_22(A, F, ...)       ZY_DO3_PIPE1_21(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_23(A, F, ...)       ZY_DO3_PIPE1_22(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_24(A, F, ...)       ZY_DO3_PIPE1_23(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_25(A, F, ...)       ZY_DO3_PIPE1_24(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_26(A, F, ...)       ZY_DO3_PIPE1_25(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_27(A, F, ...)       ZY_DO3_PIPE1_26(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_28(A, F, ...)       ZY_DO3_PIPE1_27(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_29(A, F, ...)       ZY_DO3_PIPE1_28(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_30(A, F, ...)       ZY_DO3_PIPE1_29(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_31(A, F, ...)       ZY_DO3_PIPE1_30(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_32(A, F, ...)       ZY_DO3_PIPE1_31(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_33(A, F, ...)       ZY_DO3_PIPE1_32(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_34(A, F, ...)       ZY_DO3_PIPE1_33(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_35(A, F, ...)       ZY_DO3_PIPE1_34(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_36(A, F, ...)       ZY_DO3_PIPE1_35(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_37(A, F, ...)       ZY_DO3_PIPE1_36(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_38(A, F, ...)       ZY_DO3_PIPE1_37(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_39(A, F, ...)       ZY_DO3_PIPE1_38(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_40(A, F, ...)       ZY_DO3_PIPE1_39(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_41(A, F, ...)       ZY_DO3_PIPE1_40(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_42(A, F, ...)       ZY_DO3_PIPE1_41(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_43(A, F, ...)       ZY_DO3_PIPE1_42(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_44(A, F, ...)       ZY_DO3_PIPE1_43(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_45(A, F, ...)       ZY_DO3_PIPE1_44(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_46(A, F, ...)       ZY_DO3_PIPE1_45(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_47(A, F, ...)       ZY_DO3_PIPE1_46(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_48(A, F, ...)       ZY_DO3_PIPE1_47(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_49(A, F, ...)       ZY_DO3_PIPE1_48(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_50(A, F, ...)       ZY_DO3_PIPE1_49(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_51(A, F, ...)       ZY_DO3_PIPE1_50(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_52(A, F, ...)       ZY_DO3_PIPE1_51(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_53(A, F, ...)       ZY_DO3_PIPE1_52(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_54(A, F, ...)       ZY_DO3_PIPE1_53(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_55(A, F, ...)       ZY_DO3_PIPE1_54(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_56(A, F, ...)       ZY_DO3_PIPE1_55(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_57(A, F, ...)       ZY_DO3_PIPE1_56(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_58(A, F, ...)       ZY_DO3_PIPE1_57(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_59(A, F, ...)       ZY_DO3_PIPE1_58(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_60(A, F, ...)       ZY_DO3_PIPE1_59(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_61(A, F, ...)       ZY_DO3_PIPE1_60(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_62(A, F, ...)       ZY_DO3_PIPE1_61(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_63(A, F, ...)       ZY_DO3_PIPE1_62(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_64(A, F, ...)       ZY_DO3_PIPE1_63(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_65(A, F, ...)       ZY_DO3_PIPE1_64(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_66(A, F, ...)       ZY_DO3_PIPE1_65(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_67(A, F, ...)       ZY_DO3_PIPE1_66(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_68(A, F, ...)       ZY_DO3_PIPE1_67(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_69(A, F, ...)       ZY_DO3_PIPE1_68(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_70(A, F, ...)       ZY_DO3_PIPE1_69(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_71(A, F, ...)       ZY_DO3_PIPE1_70(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_72(A, F, ...)       ZY_DO3_PIPE1_71(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_73(A, F, ...)       ZY_DO3_PIPE1_72(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_74(A, F, ...)       ZY_DO3_PIPE1_73(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_75(A, F, ...)       ZY_DO3_PIPE1_74(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_76(A, F, ...)       ZY_DO3_PIPE1_75(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_77(A, F, ...)       ZY_DO3_PIPE1_76(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_78(A, F, ...)       ZY_DO3_PIPE1_77(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_79(A, F, ...)       ZY_DO3_PIPE1_78(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_80(A, F, ...)       ZY_DO3_PIPE1_79(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_81(A, F, ...)       ZY_DO3_PIPE1_80(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_82(A, F, ...)       ZY_DO3_PIPE1_81(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_83(A, F, ...)       ZY_DO3_PIPE1_82(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_84(A, F, ...)       ZY_DO3_PIPE1_83(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_85(A, F, ...)       ZY_DO3_PIPE1_84(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_86(A, F, ...)       ZY_DO3_PIPE1_85(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_87(A, F, ...)       ZY_DO3_PIPE1_86(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_88(A, F, ...)       ZY_DO3_PIPE1_87(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_89(A, F, ...)       ZY_DO3_PIPE1_88(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_90(A, F, ...)       ZY_DO3_PIPE1_89(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_91(A, F, ...)       ZY_DO3_PIPE1_90(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_92(A, F, ...)       ZY_DO3_PIPE1_91(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_93(A, F, ...)       ZY_DO3_PIPE1_92(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_94(A, F, ...)       ZY_DO3_PIPE1_93(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_95(A, F, ...)       ZY_DO3_PIPE1_94(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_96(A, F, ...)       ZY_DO3_PIPE1_95(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_97(A, F, ...)       ZY_DO3_PIPE1_96(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_98(A, F, ...)       ZY_DO3_PIPE1_97(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_99(A, F, ...)       ZY_DO3_PIPE1_98(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_100(A, F, ...)      ZY_DO3_PIPE1_99(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_101(A, F, ...)      ZY_DO3_PIPE1_100(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_102(A, F, ...)      ZY_DO3_PIPE1_101(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_103(A, F, ...)      ZY_DO3_PIPE1_102(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_104(A, F, ...)      ZY_DO3_PIPE1_103(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_105(A, F, ...)      ZY_DO3_PIPE1_104(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_106(A, F, ...)      ZY_DO3_PIPE1_105(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_107(A, F, ...)      ZY_DO3_PIPE1_106(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_108(A, F, ...)      ZY_DO3_PIPE1_107(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_109(A, F, ...)      ZY_DO3_PIPE1_108(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_110(A, F, ...)      ZY_DO3_PIPE1_109(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_111(A, F, ...)      ZY_DO3_PIPE1_110(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_112(A, F, ...)      ZY_DO3_PIPE1_111(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_113(A, F, ...)      ZY_DO3_PIPE1_112(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_114(A, F, ...)      ZY_DO3_PIPE1_113(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_115(A, F, ...)      ZY_DO3_PIPE1_114(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_116(A, F, ...)      ZY_DO3_PIPE1_115(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_117(A, F, ...)      ZY_DO3_PIPE1_116(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_118(A, F, ...)      ZY_DO3_PIPE1_117(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_119(A, F, ...)      ZY_DO3_PIPE1_118(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_120(A, F, ...)      ZY_DO3_PIPE1_119(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_121(A, F, ...)      ZY_DO3_PIPE1_120(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_122(A, F, ...)      ZY_DO3_PIPE1_121(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_123(A, F, ...)      ZY_DO3_PIPE1_122(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_124(A, F, ...)      ZY_DO3_PIPE1_123(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_125(A, F, ...)      ZY_DO3_PIPE1_124(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_126(A, F, ...)      ZY_DO3_PIPE1_125(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_127(A, F, ...)      ZY_DO3_PIPE1_126(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_128(A, F, ...)      ZY_DO3_PIPE1_127(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)
#define ZY_DO3_PIPE1_129(A, F, ...)      ZY_DO3_PIPE1_128(ZY_APPLY(F, ZY_STRIP_PAREN(A)), __VA_ARGS__)

#define ZY_APPLY(F, ...)                 ZY_DO1_APPLY(F, __VA_ARGS__)
#define ZY_DO1_APPLY(...)                ZY_DO2_APPLY(__VA_ARGS__)
#define ZY_DO2_APPLY(F, ...)             F(__VA_ARGS__)

#define ZY_IS_EMPTY(...)                 ZY_DO1_IS_EMPTY(ZY_HAS_COMMA(__VA_ARGS__), ZY_HAS_COMMA(ZY_COMMA __VA_ARGS__), __VA_ARGS__)
#define ZY_DO1_IS_EMPTY(...)             ZY_DO2_IS_EMPTY(__VA_ARGS__)
#define ZY_DO2_IS_EMPTY(N, M, ...)       ZY_DO3_IS_EMPTY_##N##M(__VA_ARGS__)
#define ZY_DO3_IS_EMPTY_11(...)          0
#define ZY_DO3_IS_EMPTY_10(...)          0
#define ZY_DO3_IS_EMPTY_01(X)            0
#define ZY_DO3_IS_EMPTY_00(X)            ZY_DO4_IS_EMPTY(ZY_HAS_COMMA(ZY_COMMA X /**/ ()))  // Error if X is a macro function has different number of arguments.
#define ZY_DO4_IS_EMPTY(...)             ZY_DO5_IS_EMPTY(__VA_ARGS__)
#define ZY_DO5_IS_EMPTY(N)               ZY_DO6_IS_EMPTY_##N
#define ZY_DO6_IS_EMPTY_1                1
#define ZY_DO6_IS_EMPTY_0                0

/// Get the Nth element of arguments (Resolved the bug of ZY_GET1()).
#define ZY_GET(V, ...)                   ZY_DO1_GET(ZY_IS_EMPTY(__VA_ARGS__), ZY_IDENTITY(V), __VA_ARGS__)
#define ZY_DO1_GET(N, V, ...)            ZY_DO2_GET(N, ZY_IDENTITY(V), __VA_ARGS__)
#define ZY_DO2_GET(N, V, ...)            ZY_DO3_GET_##N(ZY_IDENTITY(V), __VA_ARGS__)
#define ZY_DO3_GET_1(V, ...)             ZY_GET1(V)
#define ZY_DO3_GET_0(V, ...)             ZY_GET1(__VA_ARGS__, V)

/// Count the number of arguments.
#define ZY_COUNT(...)                    ZY_GET(ZY_COUNT_V, __VA_ARGS__)

// Expand to S if ID defined as empty, i.e. "#define ID", else F
#define ZY_IF_NIL(ID, S, F)              ZY_DO1_IF_NIL(ZY_IS_EMPTY(ID), ZY_IDENTITY(S), ZY_IDENTITY(F))
#define ZY_DO1_IF_NIL(N, S, F)           ZY_DO2_IF_NIL(N, ZY_IDENTITY(S), ZY_IDENTITY(F))
#define ZY_DO2_IF_NIL(N, S, F)           ZY_DO3_IF_NIL_##N(ZY_IDENTITY(S), ZY_IDENTITY(F))
#define ZY_DO3_IF_NIL_1(S, F)            S
#define ZY_DO3_IF_NIL_0(S, F)            F

#endif  // ZY_MACRO_UTILS_H_
