name: Test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: sudo apt-get -y install cmake make gcc clang
      - run: test.sh $(mktemp -d)
