name: Test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    #   - run: sudo apt-get -y install cmake make gcc clang
      - run: find / -iname 'test.sh' 2> /dev/null
      - run: ${{ github.workspace }}/test.sh
