name: test
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update && apt-get -y install cmake make gcc clang
      - run: chmod +x ${GITHUB_WORKSPACE}/test.sh && ${GITHUB_WORKSPACE}/test.sh
